//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollageName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollageName()
        {
            this.DoctorStudyInformations = new HashSet<DoctorStudyInformation>();
        }
    
        public int CollageId { get; set; }
        public string CollageName1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorStudyInformation> DoctorStudyInformations { get; set; }
    }
}
