//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorStudyInformation
    {
        public int DoctorStudyId { get; set; }
        public int DoctorId { get; set; }
        public Nullable<int> CollageId { get; set; }
        public int StudyType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime MakeDate { get; set; }
    
        public virtual CollageName CollageName { get; set; }
        public virtual DoctorInformation DoctorInformation { get; set; }
        public virtual StudyTypeInformation StudyTypeInformation { get; set; }
    }
}
