//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorWorkplaceInformation
    {
        public int WorkPlaceId { get; set; }
        public int DoctorId { get; set; }
        public string PlaceName { get; set; }
        public int PlaceAddressId { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool PresentStatus { get; set; }
    
        public virtual DoctorInformation DoctorInformation { get; set; }
        public virtual Upazila Upazila { get; set; }
    }
}
