//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorInformation()
        {
            this.DoctorStudyInformations = new HashSet<DoctorStudyInformation>();
            this.DoctorWorkplaceInformations = new HashSet<DoctorWorkplaceInformation>();
            this.RatingAndCommands = new HashSet<RatingAndCommand>();
        }
    
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string DoctorImage { get; set; }
        public string DoctorContact { get; set; }
        public string DoctorEmail { get; set; }
        public int DoctorAddressId { get; set; }
        public int RegistrationId { get; set; }
    
        public virtual Upazila Upazila { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorStudyInformation> DoctorStudyInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorWorkplaceInformation> DoctorWorkplaceInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingAndCommand> RatingAndCommands { get; set; }
    }
}
