//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInformation
    {
        public int LoginId { get; set; }
        public int RegistrationId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.TimeSpan> LoginTime { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
