//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Smart_HealthCareEntities1 : DbContext
    {
        public Smart_HealthCareEntities1()
            : base("name=Smart_HealthCareEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollageName> CollageNames { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<DoctorInformation> DoctorInformations { get; set; }
        public virtual DbSet<DoctorStudyInformation> DoctorStudyInformations { get; set; }
        public virtual DbSet<DoctorWorkplaceInformation> DoctorWorkplaceInformations { get; set; }
        public virtual DbSet<LoginInformation> LoginInformations { get; set; }
        public virtual DbSet<PatientInformation> PatientInformations { get; set; }
        public virtual DbSet<RatingAndCommand> RatingAndCommands { get; set; }
        public virtual DbSet<StudyTypeInformation> StudyTypeInformations { get; set; }
        public virtual DbSet<Upazila> Upazilas { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<Zila> Zilas { get; set; }
    }
}
