//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInformation
    {
        public int PatientId { get; set; }
        public string PatientImage { get; set; }
        public string PatientName { get; set; }
        public string PatientMail { get; set; }
        public string PatientContact { get; set; }
        public int PatientAddressId { get; set; }
        public int RegistrationId { get; set; }
    
        public virtual Upazila Upazila { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
