//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zila
    {
        public int ZilaId { get; set; }
        public string ZilaName { get; set; }
        public int DivisionId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Upazila Upazila { get; set; }
    }
}
